export const Arabic = {
    dashboard: 'الصفحه الرئيسيه',
    admins: "المدراء",
    admin: "المشرف",
    rules: "صلاحيات",
    users: "المستخدمين",
    categories: "التصنيفات",
    sub_categories: "التصنيفات الفرعيه",
    brands: "العلامات التجارية",
    variant: "اضافات",
    dynamic_variant: 'اضافات بسعر',
    products: 'المنتجات',
    digital_products:'المنتجات الرقمية',
    orders: 'طلبات',
    reports: 'التقارير',
    notification: 'الاشعارات',
    promo_codes: 'اكواد الخصم',
    time_slot: 'اوقات العمل',
    banners: 'لافتات',
    ad_screen: 'اعلانات',
    control: 'تحكم',
    setting: 'اعدادات',
    delivery: 'توصيل',
    social_media: 'وسائل التواصل',
    currency: 'العمله',
    payment: 'الدفع',
    pages: 'الصفحات',
    total_users: 'إجمالي المستخدمين',
    total_categories: 'إجمالي التصنيفات',
    total_sub_categories: 'إجمالي التصنيفات',
    total_brands: 'إجمالي العلامات التجارية',
    total_admins: 'إجمالي المدراء',
    total_orders: 'إجمالي الطلبات',
    on_the_way: 'في الطريق',
    canceled: 'ألغيت',
    delivered: 'تم التوصيل',
    total_sales: 'إجمالي المبيعات',
    sales: 'المبيعات',
    daily: 'يومي',
    add_admin: 'إضافة المشرف',
    name: 'الإسم',
    first_name: 'الإسم الاول',
    last_name: 'الإسم الآخير',
    email: 'بريد إلكتروني',
    address: 'العنوان',
    phone: 'رقم التليفون',
    password: 'الرقم السري',
    country_code: 'كود الدوله',
    permissions: 'الأذونات',
    status: 'حالة',
    rule: 'إذن',
    full_permissions: 'أذونات كاملة',
    some_permissions: 'بعض الأذونات',
    no_permissions: 'لا أذونات',
    read_only: 'قراءه فقط',
    edit: 'تعديل',
    delete: 'مسح',
    search_by: 'البحث عن طريق',
    profile: "الحساب الشخصي",
    logout: "تسجيل الخروج",
    cancel: "إلغاء",
    submit: "إضافه",
    add: "إضافه",
    select: 'اختار',
    deleted: 'تم الحذف',
    next: 'التالي',
    previous: 'السابق',
    go_to_page: 'الذهاب الي صفحه',
    page: 'صفحه',
    of: 'من',
    category: 'تصنيف',
    add_categories: 'إضافة تصنيف',
    active: 'نشط',
    not_active: 'غير نشط',
    image: 'الصوره',
    deactive: 'تعطيل',
    english: 'اللغه الانجليزيه',
    arabic: 'اللغه العربيه',
    category_image: 'صوره التصنيف',
    close: ' اغلاق',
    price: 'السعر',
    in_stoke: 'متوفره',
    english_title: 'العنوان باللغة الانجليزية',
    english_name: 'الإسم باللغة الانجليزية',
    arabic_title: 'العنوان باللغة العربية',
    arabic_name: 'الإسم باللغة العربية',
    english_description: 'الوصف باللغة الإنجليزية',
    arabic_description: 'الوصف باللغة العربية',
    code: 'كود المنتج',
    cost: 'يكلف',
    quantity: 'كمية',
    weight: 'وزن',
    offer_price: 'سعر العرض',
    best_seller: 'الأكثر مبيعًا',
    new_in: 'الجديد في',
    offer: 'يعرض',
    images: 'الصور',
    create: 'إنشاء',
    types_by_english: 'أنواع باللغة الإنجليزية',
    types_by_arabic: 'أنواع باللغة العربية',
    add_new_value: 'إضافة قيمة جديدة',
    chosse: 'اختيار',
    has_amount: 'لديه كميه',
    available_amount: 'الكميه المتاحه'
}