export const Rules = [
    {label: 'Admin', value: 'admin'}, 
    // {label: 'Edit Admin', value: 'edit_admin'}, 
    // {label: 'Delete Admin', value: 'delete_admin'}, 
    // {label: 'Change Admin Status', value: 'change_admin_status'}, 
    {label: 'Products', value: 'products'},
    // {label: 'Edit Product', value: 'edit_product'},
    // {label: 'Delete Product', value: 'delete_product'},
    // {label: 'Change Product Status', value: 'change_product_status'},
    {label: 'Users', value: 'users'},
    // {label: 'Delete User', value: 'delete_user'},
    // {label: 'Change User Status', value: 'change_user_status'},
    {label: 'Order', value: 'order'},
    // {label: 'Delete Order', value: 'delete_order'},
    // {label: 'Change Order Status', value: 'change_order_status'},
    {label: 'Promo Code', value: 'promo_code'},
    // {label: 'Edit Promo Code', value: 'edit_promo_code'},
    // {label: 'Delete Promo Code', value: 'delete_promo_code'},
    // {label: 'Change Promo Code Status', value: 'change_promo_code_status'},
    {label: 'Categories', value: 'categories'},
    // {label: 'Edit Categories', value: 'edit_categories'},
    // {label: 'Delete Categories', value: 'delete_categories'},
    // {label: 'Change Categories Status', value: 'change_categories_status'},
    {label: 'SubCategories', value: 'sub_categories'},
    // {label: 'Edit SubCategories', value: 'edit_sub_categories'},
    // {label: 'Delete SubCategories', value: 'delete_sub_categories'},
    // {label: 'Change SubCategories Status', value: 'change_sub_categories_status'},
    {label: 'Rules', value: 'rules'},
    {label: 'Variant', value: 'variant'},
    {label: 'Banners', value: 'banners'},
    {label: 'Ad Screen', value: 'ad_screen'},
    {label: 'Social Media', value: 'social_media'},
    {label: 'Brands', value: 'brands'},
]