export const Rules = [
    {label: 'Add Admin', value: 'add_admin'}, 
    {label: 'Edit Admin', value: 'edit_admin'}, 
    {label: 'Delete Admin', value: 'delete_admin'}, 
    {label: 'Change Admin Status', value: 'change_admin_status'}, 
    {label: 'Add Product', value: 'add_product'},
    {label: 'Edit Product', value: 'edit_product'},
    {label: 'Delete Product', value: 'delete_product'},
    {label: 'Change Product Status', value: 'change_product_status'},
    {label: 'Edit User', value: 'edit_user'},
    {label: 'Delete User', value: 'delete_user'},
    {label: 'Change User Status', value: 'change_user_status'},
    {label: 'Edit Order', value: 'edit_order'},
    {label: 'Delete Order', value: 'delete_order'},
    {label: 'Change Order Status', value: 'change_order_status'},
    {label: 'Add Promo Code', value: 'add_promo_code'},
    {label: 'Edit Promo Code', value: 'edit_promo_code'},
    {label: 'Delete Promo Code', value: 'delete_promo_code'},
    {label: 'Change Promo Code Status', value: 'change_promo_code_status'},
    {label: 'Add Categories', value: 'add_categories'},
    {label: 'Edit Categories', value: 'edit_categories'},
    {label: 'Delete Categories', value: 'delete_categories'},
    {label: 'Change Categories Status', value: 'change_categories_status'},
    {label: 'Add SubCategories', value: 'add_sub_categories'},
    {label: 'Edit SubCategories', value: 'edit_sub_categories'},
    {label: 'Delete SubCategories', value: 'delete_sub_categories'},
    {label: 'Change SubCategories Status', value: 'change_sub_categories_status'},
]